import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
     <Script
	src="//www.topcreativeformat.com/a936fa072d1848ddb1985bdd0a5db4e8/invoke.js"/>
    </html>
  );
}
